// Mocks generated by Mockito 5.4.5 from annotations
// in guia_moteis/test/integration/integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:guia_moteis/features/motels/domain/use_cases/get_motels_use_case.dart'
    as _i2;
import 'package:guia_moteis/features/motels/presentation/bloc/filter/filter_bloc.dart'
    as _i3;
import 'package:guia_moteis/features/motels/presentation/bloc/motel_bloc.dart'
    as _i5;
import 'package:guia_moteis/features/motels/presentation/bloc/motel_event.dart'
    as _i7;
import 'package:guia_moteis/features/motels/presentation/bloc/motel_state.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetMotelsUseCase_0 extends _i1.SmartFake
    implements _i2.GetMotelsUseCase {
  _FakeGetMotelsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFilterBloc_1 extends _i1.SmartFake implements _i3.FilterBloc {
  _FakeFilterBloc_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMotelState_2 extends _i1.SmartFake implements _i4.MotelState {
  _FakeMotelState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MotelBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMotelBloc extends _i1.Mock implements _i5.MotelBloc {
  MockMotelBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetMotelsUseCase get getMotelsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getMotelsUseCase),
            returnValue: _FakeGetMotelsUseCase_0(
              this,
              Invocation.getter(#getMotelsUseCase),
            ),
          )
          as _i2.GetMotelsUseCase);

  @override
  _i3.FilterBloc get filterBloc =>
      (super.noSuchMethod(
            Invocation.getter(#filterBloc),
            returnValue: _FakeFilterBloc_1(
              this,
              Invocation.getter(#filterBloc),
            ),
          )
          as _i3.FilterBloc);

  @override
  _i4.MotelState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMotelState_2(this, Invocation.getter(#state)),
          )
          as _i4.MotelState);

  @override
  _i6.Stream<_i4.MotelState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.MotelState>.empty(),
          )
          as _i6.Stream<_i4.MotelState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.MotelEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.MotelEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.MotelState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.MotelEvent>(
    _i8.EventHandler<E, _i4.MotelState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i7.MotelEvent, _i4.MotelState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i4.MotelState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
